name: Docker Image CI

on:
  push:
    branches:
      - 'main'

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: wolfderechter
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push latest
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/client/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            wolfderechter/dojonode-client:latest
            wolfderechter/dojonode-client:${{ github.ref_name }}

      - name: Build and push latest
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            wolfderechter/dojonode-server:latest
            wolfderechter/dojonode-server:${{ github.ref_name }}

      - name: Create github release
        uses: ncipollo/release-action@v1
        with:
          makeLatest: true
